name: SensESP Automatic Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
          - examples/minimal_app.cpp
          - examples/analog_input.cpp
          - examples/hysteresis.cpp
          - examples/lambda_transform.cpp
          - examples/manual_networking.cpp
          - examples/minimal_app.cpp
          #- examples/relay_control.cpp
          - examples/rpm_counter.cpp
          - examples/async_repeat_sensor.cpp
          - examples/repeat_sensor_analog_input.cpp
          - examples/freertos_tasks.cpp
          - examples/raw_json.cpp
          - examples/constant_sensor.cpp
          - examples/time_counter.cpp
        target_device:
          - esp32dev
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install --upgrade platformio
      - name: Run PlatformIO
        run: ci/run-ci.sh
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
          CI_TARGET_DEVICE: ${{ matrix.target_device }}
